### ISSUE TITLE
directlfq lfq not working as expected

### ISSUE THREAD

**Issue by tobiasko** [MannLabs/directlfq#36]
**Describe the bug**
CLI command gives type error when trying to analyse DIA-NN main report. Works using the GUI.

**To Reproduce**
```
directlfq lfq -i /Users/tobiasko/Downloads/2541046/out-2024-07-11/WU305537_report.tsv -it diann_fragion_isotopes


***********************************************

     _ _               _   _     ______ _____
    | (_)             | | | |    |  ___|  _  |
  __| |_ _ __ ___  ___| |_| |    | |_  | | | |
 / _` | | '__/ _ \/ __| __| |    |  _| | | | |
| (_| | | | |  __/ (__| |_| |____| |   \ \/' /
 \__,_|_|_|  \___|\___|\__\_____/\_|    \_/\_


             * directLFQ 0.2.19 *
***********************************************


starting directLFQ
2024-07-31 15:50:21,099 - directlfq.lfq_manager - INFO - Starting directLFQ analysis.
Traceback (most recent call last):
  File "/Users/tobiasko/.directlfq/bin/directlfq", line 8, in <module>
    sys.exit(run())
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/directlfq/cli.py", line 205, in run_directlfq
    directlfq.lfq_manager.run_lfq(**kwargs)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/directlfq/lfq_manager.py", line 48, in run_lfq
    input_df = lfqutils.import_data(input_file=input_file, input_type_to_use=input_type_to_use, filter_dict=filter_dict)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/directlfq/utils.py", line 783, in import_data
    file_to_read = reformat_and_save_input_file(input_file=input_file, input_type_to_use=input_type_to_use, filter_dict=filter_dict)
  File "/Users/tobiasko/.directlfq/lib/python3.8/site-packages/directlfq/utils.py", line 803, in reformat_and_save_input_file
    config_dict_for_type['filters']=  dict(config_dict_for_type.get('filters', {}),**filter_dict)
TypeError: type object argument after ** must be a mapping, not bool
```

**Version (please complete the following information):**
 - Installation Type Pip
 -  - If no log is available, provide the following:
   - Platform information
     - system    macOS Sonoma 14.21.

**Additional context**
Could you please add a minimal CLI example to your [docu](https://github.com/MannLabs/directlfq?tab=readme-ov-file#cli). It would also help to mention that parameters/options are only explained when calling `directlfq lfq` and list them in your docu.

**Comment by ammarcsj** [comment]
Thanks for reporting this! Currently on vacation and will look into it once I'm back

**Comment by ammarcsj** [comment]
I made a new release where the issue is fixed. Let me know in case there are any other issues
